version: '3'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017/auth-db
    depends_on:
      - mongo
    command: ["./wait-for-it.sh", "mongo:27017", "--", "npm", "start"]

  product-service:
    build: ./product-service
    ports:
      - "5001:5001"
    environment: 
      MONGO_URI: mongodb://mongo:27017/product-db
    depends_on:
      - mongo
    command: ["./wait-for-it.sh", "mongo:27017", "--", "npm", "start"]

  order-service:
    build: ./order-service
    ports:
      - "5002:5002"
    environment:
      POSTGRES_URI: postgres://postgres:password@postgres:5432/order-db
    depends_on:
      - postgres
    command: ["./wait-for-it.sh", "postgres:5432", "--", "npm", "start"]

  api-gateway:
    build: ./api-gateway
    ports:
      - "4000:4000"
    depends_on:
      - auth-service
      - product-service
      - order-service
    command: ["./wait-for-it.sh", "auth-service:5000", "--", "./wait-for-it.sh", "product-service:5001", "--", "./wait-for-it.sh", "order-service:5002", "--", "npm", "start"]

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order-db
    volumes:
      - ./init-scripts/:/docker-entrypoint-initdb.d/

 
